
name: Deploy Subscription Scope

on:
  workflow_dispatch:

jobs:
  terraform:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    uses: NikolaiKleppe/common-solutions/.github/workflows/terraform-deploy-template.yml@main
    with:
      terraform_working_directory: terraform/reusable-workflow-example
      tfvars_file: terraform.tfvars
      run_apply: false
      terraform_version: 1.15.5
      apply_environment_name: terraform-apply-no-gate

      azure_subscription_id: c33f9068-3058-4127-a12d-d44382efa830

      backend_resource_group_name: rg-common-solutions-tfstate
      backend_storage_account_name: tfstatecommontc7iagly
      backend_subscription_id: c33f9068-3058-4127-a12d-d44382efa830
      backend_container_name: tfstate
      backend_key: github/simple-deploys/workflow-example.tfstate

    secrets:
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}

